<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Facades\DB;

/**
 * Seeder pour peupler la table products avec des données de test.
 * Ce seeder crée plus de 50 produits réalistes pour la boutique en ligne.
 */
class ProductSeeder extends Seeder
{
    /**
     * Liste des catégories disponibles dans la boutique.
     */
    private const CATEGORIES = [
        'Smartphones',
        'Laptops',
        'Écouteurs',
        'Tablettes',
        'Appareils Photo',
        'Accessoires',
        'Montres Connectées',
    ];

    /**
     * Exécute le seeder pour insérer les produits dans la base de données.
     * Cette méthode crée une collection variée de produits avec des données réalistes.
     */
    public function run(): void
    {
        // Désactive temporairement les contraintes de clés étrangères pour SQLite
        DB::statement('PRAGMA foreign_keys = OFF;');

        // Vide la table avant d'insérer de nouvelles données
        Product::truncate();

        // Produits initiaux fournis
        $initial_products = [
            [
                'title' => 'iPhone 15 Pro Max',
                'category' => 'Smartphones',
                'brand' => 'Apple',
                'price' => 850000,
                'stock' => 5,
                'img' => '../Images/Telephones/Iphone/phone_iphone_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Le summum de la technologie Apple avec puce A17 Pro.',
            ],
            [
                'title' => 'Galaxy S25 Ultra',
                'category' => 'Smartphones',
                'brand' => 'Samsung',
                'price' => 720000,
                'stock' => 6,
                'img' => '../Images/Telephones/Samsung/phone_samsung_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Écran 6.8" AMOLED, S Pen intégré.',
            ],
            [
                'title' => 'MacBook Pro 16" M3 Max',
                'category' => 'Laptops',
                'brand' => 'Apple',
                'price' => 2800000,
                'stock' => 2,
                'img' => '../Images/PC/Mac/pc_mac_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Puissance ultime pour pros de la création.',
            ],
            [
                'title' => 'ASUS ROG Strix G16',
                'category' => 'Laptops',
                'brand' => 'ASUS',
                'price' => 1500000,
                'stock' => 4,
                'img' => '../Images/PC/Asus/pc_asus_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'PC gamer RTX 4070, écran 165Hz.',
            ],
            [
                'title' => 'Dell XPS 15',
                'category' => 'Laptops',
                'brand' => 'Dell',
                'price' => 1600000,
                'stock' => 5,
                'img' => '../Images/PC/Dell/pc_dell_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Écran 4K OLED, design premium.',
            ],
            [
                'title' => 'HP Spectre x360 14',
                'category' => 'Laptops',
                'brand' => 'HP',
                'price' => 1350000,
                'stock' => 4,
                'img' => '../Images/PC/HP/pc_hp_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Convertible 2-en-1 haut de gamme.',
            ],
            [
                'title' => 'Casque 300 BT Pro',
                'category' => 'Écouteurs',
                'brand' => 'TechStorm',
                'price' => 65000,
                'stock' => 8,
                'img' => '../Images/Casque/casque 300 bt_1.png',
                'featured' => true,
                'new' => true,
                'desc' => 'Son Hi-Fi, réduction de bruit active.',
            ],
            [
                'title' => 'iPad Pro 12.9" M2',
                'category' => 'Tablettes',
                'brand' => 'Apple',
                'price' => 980000,
                'stock' => 4,
                'img' => '../Images/Tablette/tablette_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Écran Liquid Retina XDR, puce M2.',
            ],
            [
                'title' => 'Canon EOS R6 Mark II',
                'category' => 'Appareils Photo',
                'brand' => 'Canon',
                'price' => 1850000,
                'stock' => 3,
                'img' => '../Images/Appareil Photo/app photo_1.png',
                'featured' => true,
                'new' => true,
                'desc' => 'Hybride plein format, vidéo 6K.',
            ],
        ];

        // Produits supplémentaires pour atteindre 50+
        $additional_products = [
            // Smartphones supplémentaires
            [
                'title' => 'iPhone 14 Pro',
                'category' => 'Smartphones',
                'brand' => 'Apple',
                'price' => 650000,
                'stock' => 8,
                'img' => '../Images/Telephones/Iphone/phone_iphone_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'iPhone de génération précédente, toujours performant avec puce A16 Bionic.',
            ],
            [
                'title' => 'iPhone 13',
                'category' => 'Smartphones',
                'brand' => 'Apple',
                'price' => 480000,
                'stock' => 10,
                'img' => '../Images/Telephones/Iphone/phone_iphone_3.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Excellent rapport qualité-prix, puce A15 Bionic.',
            ],
            [
                'title' => 'Galaxy S24',
                'category' => 'Smartphones',
                'brand' => 'Samsung',
                'price' => 550000,
                'stock' => 7,
                'img' => '../Images/Telephones/Samsung/phone_samsung_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Écran AMOLED 120Hz, excellent appareil photo.',
            ],
            [
                'title' => 'Galaxy Z Fold 5',
                'category' => 'Smartphones',
                'brand' => 'Samsung',
                'price' => 1200000,
                'stock' => 3,
                'img' => '../Images/Telephones/Samsung/phone_samsung_3.jpeg',
                'featured' => true,
                'new' => false,
                'desc' => 'Smartphone pliable révolutionnaire avec écran 7.6 pouces.',
            ],
            [
                'title' => 'Galaxy A54',
                'category' => 'Smartphones',
                'brand' => 'Samsung',
                'price' => 280000,
                'stock' => 15,
                'img' => '../Images/Telephones/Samsung/phone_samsung_4.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Milieu de gamme avec excellentes performances.',
            ],
            [
                'title' => 'Pixel 8 Pro',
                'category' => 'Smartphones',
                'brand' => 'Google',
                'price' => 680000,
                'stock' => 6,
                'img' => '../Images/Telephones/Google/phone_google_1.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Meilleur appareil photo smartphone, intelligence artificielle avancée.',
            ],
            [
                'title' => 'Pixel 7a',
                'category' => 'Smartphones',
                'brand' => 'Google',
                'price' => 350000,
                'stock' => 12,
                'img' => '../Images/Telephones/Google/phone_google_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Excellent rapport qualité-prix avec fonctionnalités Pixel.',
            ],
            [
                'title' => 'OnePlus 12',
                'category' => 'Smartphones',
                'brand' => 'OnePlus',
                'price' => 520000,
                'stock' => 9,
                'img' => '../Images/Telephones/OnePlus/phone_oneplus_1.jpeg',
                'featured' => false,
                'new' => true,
                'desc' => 'Charge rapide 100W, écran AMOLED 120Hz.',
            ],
            [
                'title' => 'Xiaomi 14 Pro',
                'category' => 'Smartphones',
                'brand' => 'Xiaomi',
                'price' => 580000,
                'stock' => 8,
                'img' => '../Images/Telephones/Xiaomi/phone_xiaomi_1.jpeg',
                'featured' => false,
                'new' => true,
                'desc' => 'Partenariat Leica pour la photo, performances exceptionnelles.',
            ],
            [
                'title' => 'Xiaomi Redmi Note 13 Pro',
                'category' => 'Smartphones',
                'brand' => 'Xiaomi',
                'price' => 220000,
                'stock' => 20,
                'img' => '../Images/Telephones/Xiaomi/phone_xiaomi_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Meilleur rapport qualité-prix du marché.',
            ],

            // Laptops supplémentaires
            [
                'title' => 'MacBook Air 13" M2',
                'category' => 'Laptops',
                'brand' => 'Apple',
                'price' => 950000,
                'stock' => 7,
                'img' => '../Images/PC/Mac/pc_mac_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Ultraportable léger et silencieux, parfait pour le quotidien.',
            ],
            [
                'title' => 'MacBook Air 15" M3',
                'category' => 'Laptops',
                'brand' => 'Apple',
                'price' => 1250000,
                'stock' => 5,
                'img' => '../Images/PC/Mac/pc_mac_3.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'Grand écran dans un châssis ultraportable.',
            ],
            [
                'title' => 'ASUS ZenBook 14',
                'category' => 'Laptops',
                'brand' => 'ASUS',
                'price' => 780000,
                'stock' => 6,
                'img' => '../Images/PC/Asus/pc_asus_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Design élégant, performances solides pour le travail.',
            ],
            [
                'title' => 'ASUS TUF Gaming A15',
                'category' => 'Laptops',
                'brand' => 'ASUS',
                'price' => 980000,
                'stock' => 8,
                'img' => '../Images/PC/Asus/pc_asus_3.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Gaming abordable avec RTX 4060.',
            ],
            [
                'title' => 'Dell Inspiron 15',
                'category' => 'Laptops',
                'brand' => 'Dell',
                'price' => 550000,
                'stock' => 12,
                'img' => '../Images/PC/Dell/pc_dell_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'PC polyvalent pour usage familial et professionnel.',
            ],
            [
                'title' => 'Dell Alienware m16',
                'category' => 'Laptops',
                'brand' => 'Dell',
                'price' => 2200000,
                'stock' => 3,
                'img' => '../Images/PC/Dell/pc_dell_3.jpeg',
                'featured' => true,
                'new' => true,
                'desc' => 'PC gaming haut de gamme avec RTX 4080.',
            ],
            [
                'title' => 'HP Pavilion 15',
                'category' => 'Laptops',
                'brand' => 'HP',
                'price' => 480000,
                'stock' => 10,
                'img' => '../Images/PC/HP/pc_hp_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'PC abordable pour la bureautique et le multimédia.',
            ],
            [
                'title' => 'HP Omen 16',
                'category' => 'Laptops',
                'brand' => 'HP',
                'price' => 1450000,
                'stock' => 5,
                'img' => '../Images/PC/HP/pc_hp_3.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Gaming performant avec écran 165Hz.',
            ],
            [
                'title' => 'Lenovo ThinkPad X1 Carbon',
                'category' => 'Laptops',
                'brand' => 'Lenovo',
                'price' => 1380000,
                'stock' => 4,
                'img' => '../Images/PC/Lenovo/pc_lenovo_1.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'PC professionnel ultraléger et robuste.',
            ],
            [
                'title' => 'Lenovo Legion 5 Pro',
                'category' => 'Laptops',
                'brand' => 'Lenovo',
                'price' => 1280000,
                'stock' => 6,
                'img' => '../Images/PC/Lenovo/pc_lenovo_2.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Excellent PC gaming avec bon rapport qualité-prix.',
            ],
            [
                'title' => 'MSI Katana 15',
                'category' => 'Laptops',
                'brand' => 'MSI',
                'price' => 920000,
                'stock' => 7,
                'img' => '../Images/PC/MSI/pc_msi_1.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Gaming accessible avec RTX 4050.',
            ],

            // Écouteurs et Casques
            [
                'title' => 'AirPods Pro 2',
                'category' => 'Écouteurs',
                'brand' => 'Apple',
                'price' => 180000,
                'stock' => 15,
                'img' => '../Images/Casque/casque_airpods_1.png',
                'featured' => true,
                'new' => false,
                'desc' => 'Réduction de bruit active adaptative, audio spatial.',
            ],
            [
                'title' => 'AirPods Max',
                'category' => 'Écouteurs',
                'brand' => 'Apple',
                'price' => 420000,
                'stock' => 5,
                'img' => '../Images/Casque/casque_airpods_2.png',
                'featured' => true,
                'new' => false,
                'desc' => 'Casque over-ear premium avec audio spatial.',
            ],
            [
                'title' => 'Sony WH-1000XM5',
                'category' => 'Écouteurs',
                'brand' => 'Sony',
                'price' => 280000,
                'stock' => 10,
                'img' => '../Images/Casque/casque_sony_1.png',
                'featured' => true,
                'new' => false,
                'desc' => 'Meilleure réduction de bruit du marché.',
            ],
            [
                'title' => 'Sony WF-1000XM5',
                'category' => 'Écouteurs',
                'brand' => 'Sony',
                'price' => 210000,
                'stock' => 12,
                'img' => '../Images/Casque/casque_sony_2.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Écouteurs true wireless haut de gamme.',
            ],
            [
                'title' => 'Bose QuietComfort Ultra',
                'category' => 'Écouteurs',
                'brand' => 'Bose',
                'price' => 320000,
                'stock' => 6,
                'img' => '../Images/Casque/casque_bose_1.png',
                'featured' => false,
                'new' => true,
                'desc' => 'Confort exceptionnel et son immersif.',
            ],
            [
                'title' => 'Samsung Galaxy Buds2 Pro',
                'category' => 'Écouteurs',
                'brand' => 'Samsung',
                'price' => 150000,
                'stock' => 14,
                'img' => '../Images/Casque/casque_samsung_1.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Intégration parfaite avec Galaxy, réduction de bruit.',
            ],
            [
                'title' => 'JBL Tune 770NC',
                'category' => 'Écouteurs',
                'brand' => 'JBL',
                'price' => 95000,
                'stock' => 18,
                'img' => '../Images/Casque/casque_jbl_1.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Excellent rapport qualité-prix avec réduction de bruit.',
            ],

            // Tablettes
            [
                'title' => 'iPad Air 11" M2',
                'category' => 'Tablettes',
                'brand' => 'Apple',
                'price' => 580000,
                'stock' => 8,
                'img' => '../Images/Tablette/tablette_2.jpeg',
                'featured' => false,
                'new' => true,
                'desc' => 'Tablette puissante et polyvalente.',
            ],
            [
                'title' => 'iPad 10',
                'category' => 'Tablettes',
                'brand' => 'Apple',
                'price' => 350000,
                'stock' => 12,
                'img' => '../Images/Tablette/tablette_3.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Tablette d\'entrée de gamme avec design moderne.',
            ],
            [
                'title' => 'Samsung Galaxy Tab S9 Ultra',
                'category' => 'Tablettes',
                'brand' => 'Samsung',
                'price' => 950000,
                'stock' => 4,
                'img' => '../Images/Tablette/tablette_4.jpeg',
                'featured' => true,
                'new' => false,
                'desc' => 'Écran AMOLED géant 14.6", S Pen inclus.',
            ],
            [
                'title' => 'Samsung Galaxy Tab A9+',
                'category' => 'Tablettes',
                'brand' => 'Samsung',
                'price' => 180000,
                'stock' => 15,
                'img' => '../Images/Tablette/tablette_5.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Tablette abordable pour le divertissement.',
            ],
            [
                'title' => 'Microsoft Surface Pro 9',
                'category' => 'Tablettes',
                'brand' => 'Microsoft',
                'price' => 1100000,
                'stock' => 6,
                'img' => '../Images/Tablette/tablette_6.jpeg',
                'featured' => false,
                'new' => false,
                'desc' => 'Tablette 2-en-1 avec Windows 11, parfaite pour la productivité.',
            ],

            // Appareils Photo
            [
                'title' => 'Sony Alpha A7 IV',
                'category' => 'Appareils Photo',
                'brand' => 'Sony',
                'price' => 1680000,
                'stock' => 4,
                'img' => '../Images/Appareil Photo/app photo_2.png',
                'featured' => true,
                'new' => false,
                'desc' => 'Hybride polyvalent 33MP, vidéo 4K 60fps.',
            ],
            [
                'title' => 'Canon EOS R8',
                'category' => 'Appareils Photo',
                'brand' => 'Canon',
                'price' => 1250000,
                'stock' => 5,
                'img' => '../Images/Appareil Photo/app photo_3.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Hybride plein format compact et abordable.',
            ],
            [
                'title' => 'Nikon Z8',
                'category' => 'Appareils Photo',
                'brand' => 'Nikon',
                'price' => 2950000,
                'stock' => 2,
                'img' => '../Images/Appareil Photo/app photo_4.png',
                'featured' => true,
                'new' => true,
                'desc' => 'Appareil professionnel 45.7MP, vidéo 8K.',
            ],
            [
                'title' => 'Fujifilm X-T5',
                'category' => 'Appareils Photo',
                'brand' => 'Fujifilm',
                'price' => 1480000,
                'stock' => 5,
                'img' => '../Images/Appareil Photo/app photo_5.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Design rétro, capteur APS-C 40MP.',
            ],
            [
                'title' => 'GoPro Hero 12 Black',
                'category' => 'Appareils Photo',
                'brand' => 'GoPro',
                'price' => 380000,
                'stock' => 10,
                'img' => '../Images/Appareil Photo/app photo_6.png',
                'featured' => false,
                'new' => true,
                'desc' => 'Caméra d\'action 5.3K, stabilisation HyperSmooth.',
            ],

            // Accessoires
            [
                'title' => 'Chargeur USB-C 65W',
                'category' => 'Accessoires',
                'brand' => 'Anker',
                'price' => 35000,
                'stock' => 25,
                'img' => '../Images/Accessoires/acc_1.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Chargeur rapide compatible tous appareils USB-C.',
            ],
            [
                'title' => 'Batterie externe 20000mAh',
                'category' => 'Accessoires',
                'brand' => 'Anker',
                'price' => 48000,
                'stock' => 20,
                'img' => '../Images/Accessoires/acc_2.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Power bank grande capacité avec charge rapide.',
            ],
            [
                'title' => 'Clavier Mécanique RGB',
                'category' => 'Accessoires',
                'brand' => 'Logitech',
                'price' => 125000,
                'stock' => 12,
                'img' => '../Images/Accessoires/acc_3.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Clavier gaming avec switches mécaniques.',
            ],
            [
                'title' => 'Souris Sans Fil MX Master 3S',
                'category' => 'Accessoires',
                'brand' => 'Logitech',
                'price' => 85000,
                'stock' => 15,
                'img' => '../Images/Accessoires/acc_4.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Souris ergonomique pour professionnels.',
            ],
            [
                'title' => 'Hub USB-C 7-en-1',
                'category' => 'Accessoires',
                'brand' => 'Belkin',
                'price' => 68000,
                'stock' => 18,
                'img' => '../Images/Accessoires/acc_5.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Hub multiport HDMI, USB, Ethernet, SD.',
            ],
            [
                'title' => 'Support Laptop Ergonomique',
                'category' => 'Accessoires',
                'brand' => 'Rain Design',
                'price' => 52000,
                'stock' => 14,
                'img' => '../Images/Accessoires/acc_6.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Support en aluminium pour meilleure posture.',
            ],
            [
                'title' => 'Webcam 4K Pro',
                'category' => 'Accessoires',
                'brand' => 'Logitech',
                'price' => 145000,
                'stock' => 8,
                'img' => '../Images/Accessoires/acc_7.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Webcam 4K HDR avec mise au point automatique.',
            ],

            // Montres Connectées
            [
                'title' => 'Apple Watch Series 9',
                'category' => 'Montres Connectées',
                'brand' => 'Apple',
                'price' => 380000,
                'stock' => 10,
                'img' => '../Images/Montres/watch_1.png',
                'featured' => true,
                'new' => true,
                'desc' => 'Écran lumineux, suivi santé complet.',
            ],
            [
                'title' => 'Apple Watch Ultra 2',
                'category' => 'Montres Connectées',
                'brand' => 'Apple',
                'price' => 720000,
                'stock' => 4,
                'img' => '../Images/Montres/watch_2.png',
                'featured' => true,
                'new' => true,
                'desc' => 'Montre d\'aventure robuste, autonomie extrême.',
            ],
            [
                'title' => 'Samsung Galaxy Watch 6',
                'category' => 'Montres Connectées',
                'brand' => 'Samsung',
                'price' => 280000,
                'stock' => 12,
                'img' => '../Images/Montres/watch_3.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Montre élégante avec suivi santé avancé.',
            ],
            [
                'title' => 'Garmin Fenix 7',
                'category' => 'Montres Connectées',
                'brand' => 'Garmin',
                'price' => 580000,
                'stock' => 6,
                'img' => '../Images/Montres/watch_4.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Montre multisport GPS avec cartographie.',
            ],
            [
                'title' => 'Fitbit Sense 2',
                'category' => 'Montres Connectées',
                'brand' => 'Fitbit',
                'price' => 220000,
                'stock' => 15,
                'img' => '../Images/Montres/watch_5.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Montre santé avec gestion du stress.',
            ],
            [
                'title' => 'Xiaomi Watch 2 Pro',
                'category' => 'Montres Connectées',
                'brand' => 'Xiaomi',
                'price' => 180000,
                'stock' => 18,
                'img' => '../Images/Montres/watch_6.png',
                'featured' => false,
                'new' => false,
                'desc' => 'Excellent rapport qualité-prix avec GPS.',
            ],
        ];

        // Fusion des deux tableaux
        $all_products = array_merge($initial_products, $additional_products);

        // Insertion de tous les produits
        foreach ($all_products as $product_data) {
            Product::create($product_data);
        }

        // Réactive les contraintes de clés étrangères
        DB::statement('PRAGMA foreign_keys = ON;');

        $this->command->info('✅ ' . count($all_products) . ' produits créés avec succès !');
    }
}
